DEVPROD-6448:
evergreen-ci/ui pull request #273
Opened 2024-07-26 19:26 UTC by sophiabarness

DEVPROD-6448

### Description

### Screenshots

### Testing

### Evergreen PR

2024-07-31 14:23 UTC, SupaJoon requested changes
@sophiabarness Your code change allows the page to work but I think it doesn't fix the root cause of the issue. Clicking the link in the task duration table navigates to:

```/task/mongodb_mongo_master_linux_64_debug_required_display_sharding_auto_bootstrap_patch_7784fe68588c5559b326c6423c0c09e35b7b156f_660f15f6ffa54e0007d1b2f7_24_04_04_21_05_18?sortBy=STATUS&sortDir=ASC```

and refreshing that page navigates to:

```/task/mongodb_mongo_master_linux_64_debug_required_display_sharding_auto_bootstrap_patch_7784fe68588c5559b326c6423c0c09e35b7b156f_660f15f6ffa54e0007d1b2f7_24_04_04_21_05_18/execution-tasks?execution=1&sortBy=STATUS&sortDir=ASC```

The underlying issue will be fixed when the link navigation matches the same URL as the page refresh.

2024-08-02 19:43 UTC, minnakt requested changes
nit. The PR title should be a description of what you changed, and is not always equivalent to the title of the JIRA ticket. It should begin with a verb in the imperative mood — here is the [guide](https://docs.google.com/document/d/1LJHPjLb_bUZxv-l_9Y61kitzAg7u-13I5DjOhZ-deBA/edit#heading=h.i9oftc5069w9) for how to write PR descriptions

2024-08-02 19:43 UTC, minnakt commented on apps/spruce/src/pages/version/taskDuration/TaskDurationTable.tsx
> +        }) => <TaskLink taskId={id} taskName={getValue()} execution={0} />,
the execution may not always be 0; we should link to the latest execution

2024-08-02 19:43 UTC, minnakt commented on apps/spruce/src/pages/version/taskDuration/TaskDurationTable.tsx
>              original: { id },
you can probably use this object to get the execution

2024-08-02 19:43 UTC, minnakt commented on apps/spruce/src/pages/version/taskDuration/TaskDurationTable.tsx
>              // @ts-expect-error: FIXME. This comment was added by an automated script.
the type errors can probably be fixed by typing the columns with `LGColumnDef<type_here>`

2024-08-05 21:28 UTC, minnakt approved these changes
nit. I slightly prefer the PR title to be in sentence case rather than title case. i.e. `Update Task Duration Links to Route to Latest Execution` => `Update task duration links to route to latest execution`

nice job fixing those type errors!

2024-08-05 21:28 UTC, minnakt commented on apps/spruce/src/pages/version/taskDuration/TaskDurationTable.tsx
> +  VersionTaskDurationsQuery["version"]["tasks"]["data"][0];
let's use the `Unpacked` util
```suggestion
type TaskDurationColumnData =
  Unpacked<VersionTaskDurationsQuery["version"]["tasks"]["data"]>;
```

2024-08-05 21:28 UTC, minnakt commented on apps/spruce/src/pages/version/taskDuration/TaskDurationTable.tsx
>    tasks: VersionTaskDurationsQuery["version"]["tasks"]["data"];
This can be typed as 
```suggestion
  tasks: TaskDurationColumnData[];
```

2024-08-05 21:28 UTC, minnakt commented on apps/spruce/src/pages/version/taskDuration/TaskDurationTable.tsx
> +type TaskDurationColumnData =
Maybe the type should be called `TaskDurationData` (column seems redundant)

2024-08-06 18:50 UTC, SupaJoon approved these changes

2024-08-07 15:58 UTC, merged