DEVPROD-8373 Update spruce and parsley analytics attributes to use dot notation
evergreen-ci/ui pull request #315
Opened 2024-08-16 13:52 UTC by khelif96

DEVPROD-8373

### Description
This PR updates all of the remaining spruce and parsley analytics attributes to utilize dot notation which is recommended/required by OTEL. Also removes the usage of complex structs since those are not supported. 
In a future PR I will introduce strict typescript enforcement of structs so that they are not complex.

**Have you have updated the analytics documentation if necessary?**  
Yes

### Evergreen PR

2024-08-20 16:01 UTC, SupaJoon requested changes
looking for feedback/answer to my question on how the dot notation will be parsed later on

2024-08-20 16:01 UTC, SupaJoon commented on apps/spruce/src/pages/spawn/spawnVolume/spawnVolumeTableActions/MigrateVolumeModal.tsx
> +      "is.volume.migration": true,
maybe consider concatenating volume.migration

2024-08-21 15:13 UTC, khelif96 commented on apps/spruce/src/analytics/spawn/useSpawnAnalytics.ts
> +      "no.expire": boolean;
I updated this alongside the rest of the params with the `host` prefix e.g `host.is.unexpirable`, `host.is.workstation` So it is easier to group by host attributes.

2024-08-21 15:15 UTC, khelif96 commented on apps/spruce/src/pages/spawn/spawnVolume/spawnVolumeTableActions/EditVolumeModal.tsx
> +      "volume.no.expire": mutationInput.noExpiration,
Updated to `volume.is.unexpirable` for consistency with the host attributes

2024-08-21 15:30 UTC, khelif96 commented on apps/spruce/src/analytics/patches/useProjectPatchesAnalytics.ts
> +      "filter.include.commit.queue": boolean;
This is the standard naming convention for otel attributes. I also updated some attributes to use namespaces as how they are described in the docs below
 https://opentelemetry.io/docs/specs/semconv/general/attribute-naming/

2024-08-21 16:47 UTC, SupaJoon commented on apps/spruce/src/analytics/patches/useProjectPatchesAnalytics.ts
> +      "filter.include.commit.queue": boolean;
Neat, the doc states that namespaces are not meant to be hierarchical and are actually meant for preventing name clashes.

2024-08-21 16:48 UTC, SupaJoon approved these changes

2024-08-21 16:58 UTC, merged