DEVPROD-7340 Part A Move ConditionalWrapper to lib and setup vitest for jsdom testing in lib
evergreen-ci/ui pull request #398
Opened 2024-09-19 16:09 UTC by khelif96

DEVPROD-7340

### Description
This is the first part in a series of PRs in order to help breakup the setup work required to move the LG table component over to the lib package.

Move the ConditionalWrapper component to lib as well as initialize the testing infrastructure in the lib package to support jsdom based matchers.

2024-09-19 16:38 UTC, sophstad requested changes

2024-09-19 16:38 UTC, sophstad commented on packages/lib/config/vitest/setupTests.ts
This needs to be referenced in `vitest.config.ts` to take effect

2024-09-19 16:38 UTC, sophstad commented on packages/lib/config/vitest/global-setup.ts
Same as above

2024-09-20 21:22 UTC, khelif96 commented on packages/lib/config/vitest/setupTests.ts
Thanks!

2024-09-23 15:09 UTC, minnakt commented on packages/lib/config/vitest/setupTests.ts
> +})();
is this block necessary? If not, could we delete it, and if it is, can we leave a comment about why it's necessary?

2024-09-23 18:19 UTC, merged