DEVPROD-13052 Create error boundary and handle errors on waterfall page
evergreen-ci/ui pull request #553
Opened 2024-12-26 20:27 UTC by khelif96

DEVPROD-13052

### Description
Since we use `useSuspenseQuery` any errors need to be handled by an ErrorBoundary. To prevent the errors from propagating up to the central ErrorBoundary that wrap the entire app I created a custom one for just the Waterfall page.
We didn't have designs for this so I came up with one, open to suggestions.

### Screenshots
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/9f527608-98dc-4785-938e-b6779bad7fe6" />

### Testing
Wrote unit tests

2025-01-06 19:28 UTC, sophstad requested changes

2025-01-06 19:28 UTC, sophstad commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +            data-cy="waterfall-skeleton"
I think disabling animations here may make sense, to me the motion implies loading but there's nothing incoming to render.
```suggestion
            data-cy="waterfall-skeleton"
            enableAnimations={false}
```

2025-01-06 19:28 UTC, sophstad commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +          <TableSkeleton
Can we pull out this skeleton into a separate component to reuse with the loading state?

2025-01-06 19:28 UTC, sophstad commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +                  Reset Page
Instead of "Reset Page," I think something like "Return to waterfall" may be a little more user friendly

2025-01-06 19:28 UTC, sophstad commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +                <Button onClick={this.handleResetPage} variant="primary">
Imo an arrow looks nice since this button kinda functions as a link
<img width="703" alt="image" src="https://github.com/user-attachments/assets/3d4e7f75-41b3-4035-8d32-8326c8507e98" />
```suggestion
                <Button onClick={this.handleResetPage} variant="primary"                   rightGlyph={<Icon glyph="ArrowRight" />}>
```

2025-01-06 19:28 UTC, sophstad commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +const Container = styled.div`
Not sure exactly what rule is causing this overflow, but a horizontal scrollbar is introduced on this page (there wasn't one when I was on the previous waterfall page)
<img width="1559" alt="image" src="https://github.com/user-attachments/assets/e0144775-9a5a-4249-b9fa-7508834cffcb" />

2025-01-06 22:02 UTC, khelif96 commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +class WaterfallErrorBoundary extends React.Component<
I'm surprised there isn't a _hooky_ way of creating ErrorBoundarys yet.

2025-01-06 22:04 UTC, khelif96 commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +const Container = styled.div`
I think its a combination of the `position:absolute` and the `width: 100%` causing it. Since now it represents 100% of the view window instead of the container.

2025-01-07 17:24 UTC, sophstad requested changes

2025-01-07 17:24 UTC, sophstad commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
Using the project select dropdown from this page doesn't work, I think that would be a pretty common use case worth fixing.

2025-01-07 17:24 UTC, sophstad commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +  width: fill-available;
Nice rule 😁 it doesn't work as well in safari lol but what can you do

2025-01-07 17:51 UTC, khelif96 commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
> +  width: fill-available;
:shakes_fist_at_safari: [caniuse](https://caniuse.com/?search=fill-available) says it was supported smh :( Replaced it with vw

2025-01-07 17:51 UTC, khelif96 commented on apps/spruce/src/pages/waterfall/WaterfallErrorBoundary/index.tsx
Fixed!

2025-01-07 21:58 UTC, sophstad approved these changes
Not sure why this e2e test is consistently failing across PRs but LGTM!

2025-01-07 23:12 UTC, merged